# Generated by Django 5.2.12 on 2026-08-17 07:30

import apps.core.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the name when left blank.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are hidden from the public API.')),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, default='', help_text='Browser tab / search result title. Auto-generated when blank.', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='', help_text='Search result snippet, ideally under 160 characters. Auto-generated when blank.')),
                ('keywords', models.CharField(blank=True, default='', help_text='Comma separated keywords. Auto-generated when blank.', max_length=500)),
                ('canonical_url', models.CharField(blank=True, default='', help_text='Canonical path or absolute URL. Auto-generated when blank.', max_length=500)),
                ('robots', models.CharField(choices=[('index,follow', 'Index and follow links'), ('index,nofollow', 'Index but do not follow links'), ('noindex,follow', 'Do not index but follow links'), ('noindex,nofollow', 'Do not index or follow links')], default='index,follow', help_text='How search engines should treat this page.', max_length=32)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.CharField(blank=True, default='', help_text='Absolute URL of the share image.', max_length=500)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=32)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_description', models.TextField(blank=True, default='')),
                ('twitter_image', models.CharField(blank=True, default='', max_length=500)),
                ('schema_json', models.JSONField(blank=True, help_text='schema.org JSON-LD. Auto-generated when blank.', null=True)),
                ('seo_generated', models.JSONField(blank=True, default=dict, editable=False)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier. Generated from the title when left blank.', max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Unpublished entries are hidden from the public API.')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this entry on listing pages.')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Ties fall back to newest-first.')),
                ('title', models.CharField(help_text='Event name as shown on the website.', max_length=255)),
                ('summary', models.TextField(blank=True, default='', help_text='Short teaser shown on listing cards. Generated from the content when blank.')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Full event description.')),
                ('event_date', models.DateField(blank=True, help_text='When the event takes place / took place.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Last day, for multi-day events.', null=True)),
                ('venue', models.CharField(blank=True, default='', max_length=255)),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments this event belongs to. Leave empty for university-wide events.', related_name='events', to='core.department')),
                ('category', models.ForeignKey(help_text='Upcoming, Achievements, ...', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventcategory')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['display_order', '-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Ties fall back to newest-first.')),
                ('image', apps.core.fields.SVGImageField(help_text='Photo file.', upload_to='events/gallery/')),
                ('alt', models.CharField(blank=True, default='', help_text='Alt text for accessibility and SEO.', max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=500)),
                ('is_featured', models.BooleanField(default=False, help_text="Use this photo as the event's highlight image. Only one photo per event can be featured.")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', 'display_order'], name='events_even_is_publ_525324_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'is_published'], name='events_even_categor_a428ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_featured', True)), fields=('event',), name='unique_featured_image_per_event'),
        ),
    ]
