# Generated by Django 5.2.12 on 2026-08-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Finish time. Optional; shown only when a start time is set.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, help_text="Start time shown as the event's 'Timing'. Optional.", null=True),
        ),
    ]
