# Generated by Django 5.2.12 on 2026-08-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course'),
        ('events', '0004_website_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text="Programmes this event relates to. Powers the website's Courses filter.", related_name='events', to='core.course'),
        ),
    ]
