# Generated by Django 5.2.12 on 2026-08-18 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the name when left blank.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are hidden from the public API.')),
                ('short_name', models.CharField(blank=True, default='', help_text="Abbreviation shown in compact UI, e.g. 'EMBA'.", max_length=32)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
    ]
