# Generated by Django 5.2.12 on 2026-08-17 07:30

import apps.core.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the name when left blank.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are hidden from the public API.')),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, default='', help_text='Browser tab / search result title. Auto-generated when blank.', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='', help_text='Search result snippet, ideally under 160 characters. Auto-generated when blank.')),
                ('keywords', models.CharField(blank=True, default='', help_text='Comma separated keywords. Auto-generated when blank.', max_length=500)),
                ('canonical_url', models.CharField(blank=True, default='', help_text='Canonical path or absolute URL. Auto-generated when blank.', max_length=500)),
                ('robots', models.CharField(choices=[('index,follow', 'Index and follow links'), ('index,nofollow', 'Index but do not follow links'), ('noindex,follow', 'Do not index but follow links'), ('noindex,nofollow', 'Do not index or follow links')], default='index,follow', help_text='How search engines should treat this page.', max_length=32)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.CharField(blank=True, default='', help_text='Absolute URL of the share image.', max_length=500)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=32)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_description', models.TextField(blank=True, default='')),
                ('twitter_image', models.CharField(blank=True, default='', max_length=500)),
                ('schema_json', models.JSONField(blank=True, help_text='schema.org JSON-LD. Auto-generated when blank.', null=True)),
                ('seo_generated', models.JSONField(blank=True, default=dict, editable=False)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier. Generated from the title when left blank.', max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Unpublished entries are hidden from the public API.')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this entry on listing pages.')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Ties fall back to newest-first.')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='', help_text='Short teaser shown on listing cards. Generated from the content when blank.')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Full article body.')),
                ('featured_image', apps.core.fields.SVGImageField(blank=True, help_text='Cover image shown on listing cards and social shares.', null=True, upload_to='blogs/featured/')),
                ('featured_image_alt', models.CharField(blank=True, default='', help_text='Alt text for the cover image.', max_length=255)),
                ('published_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Date shown on the post.')),
                ('author_name', models.CharField(blank=True, default='', help_text='Byline shown on the post.', max_length=255)),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments this post belongs to. Leave empty for university-wide posts.', related_name='blogs', to='core.department')),
                ('categories', models.ManyToManyField(blank=True, help_text='One or more topics this post belongs to.', related_name='blogs', to='blogs.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['display_order', '-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Ties fall back to newest-first.')),
                ('image', apps.core.fields.SVGImageField(upload_to='blogs/gallery/')),
                ('alt', models.CharField(blank=True, default='', help_text='Alt text for accessibility and SEO.', max_length=255)),
                ('caption', models.CharField(blank=True, default='', max_length=500)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blogs.blog')),
            ],
            options={
                'verbose_name': 'Blog Image',
                'verbose_name_plural': 'Blog Images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['is_published', '-published_date'], name='blogs_blog_is_publ_a62999_idx'),
        ),
    ]
