# Generated by Django 5.2.12 on 2026-08-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_website_categories'),
        ('core', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text="Programmes this post relates to. Powers the website's Courses filter.", related_name='blogs', to='core.course'),
        ),
    ]
