# Generated by Django 5.2.12 on 2026-08-17 07:30

import apps.core.fields
import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from the name when left blank.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are hidden from the public API.')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['display_order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, default='', help_text='Browser tab / search result title. Auto-generated when blank.', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='', help_text='Search result snippet, ideally under 160 characters. Auto-generated when blank.')),
                ('keywords', models.CharField(blank=True, default='', help_text='Comma separated keywords. Auto-generated when blank.', max_length=500)),
                ('canonical_url', models.CharField(blank=True, default='', help_text='Canonical path or absolute URL. Auto-generated when blank.', max_length=500)),
                ('robots', models.CharField(choices=[('index,follow', 'Index and follow links'), ('index,nofollow', 'Index but do not follow links'), ('noindex,follow', 'Do not index but follow links'), ('noindex,nofollow', 'Do not index or follow links')], default='index,follow', help_text='How search engines should treat this page.', max_length=32)),
                ('author', models.CharField(blank=True, default='', max_length=255)),
                ('og_title', models.CharField(blank=True, default='', max_length=255)),
                ('og_description', models.TextField(blank=True, default='')),
                ('og_image', models.CharField(blank=True, default='', help_text='Absolute URL of the share image.', max_length=500)),
                ('twitter_card', models.CharField(default='summary_large_image', max_length=32)),
                ('twitter_title', models.CharField(blank=True, default='', max_length=255)),
                ('twitter_description', models.TextField(blank=True, default='')),
                ('twitter_image', models.CharField(blank=True, default='', max_length=500)),
                ('schema_json', models.JSONField(blank=True, help_text='schema.org JSON-LD. Auto-generated when blank.', null=True)),
                ('seo_generated', models.JSONField(blank=True, default=dict, editable=False)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier. Generated from the title when left blank.', max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Unpublished entries are hidden from the public API.')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this entry on listing pages.')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Ties fall back to newest-first.')),
                ('name', models.CharField(help_text='Full name as it should appear publicly.', max_length=255)),
                ('image', apps.core.fields.SVGImageField(blank=True, help_text='Profile photo. Portrait orientation works best.', null=True, upload_to='faculty/photos/')),
                ('image_alt', models.CharField(blank=True, default='', help_text='Alt text for the photo.', max_length=255)),
                ('qualification', models.CharField(blank=True, default='', help_text="Degrees and certifications, e.g. 'Ph.D., M.Tech, B.Tech'.", max_length=500)),
                ('mail_id', models.EmailField(blank=True, default='', help_text='Optional. Shown publicly when filled.', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Optional. Shown publicly when filled.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces and + ( ) - only).', regex='^[0-9+()\\-\\s]{6,20}$')])),
                ('profile_link', models.URLField(blank=True, default='', help_text='Optional personal site, Scholar or ORCID profile.')),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments this person belongs to. More than one is allowed.', related_name='faculty_members', to='core.department')),
                ('designation', models.ForeignKey(help_text='Job title.', on_delete=django.db.models.deletion.PROTECT, related_name='faculty_members', to='faculty.designation')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculty',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Ties fall back to newest-first.')),
                ('image', apps.core.fields.SVGImageField(upload_to='faculty/banners/')),
                ('alt', models.CharField(blank=True, default='', help_text='Alt text for the banner.', max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'Faculty Banner',
                'verbose_name_plural': 'Faculty Banners',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FacultySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Lower numbers appear first. Ties fall back to newest-first.')),
                ('heading', models.CharField(help_text="Section title, e.g. 'Publications'.", max_length=255)),
                ('content', ckeditor.fields.RichTextField(help_text='Section body.')),
                ('is_visible', models.BooleanField(default=True, help_text='Untick to hide this section without deleting it.')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='faculty.faculty')),
            ],
            options={
                'verbose_name': 'Profile Section',
                'verbose_name_plural': 'Profile Sections',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['is_published', 'display_order'], name='faculty_fac_is_publ_f8e19f_idx'),
        ),
        migrations.AddConstraint(
            model_name='facultysection',
            constraint=models.UniqueConstraint(fields=('faculty', 'heading'), name='unique_section_heading_per_faculty'),
        ),
    ]
