# Generated by Django 5.2.12 on 2026-08-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='external_image_url',
            field=models.URLField(blank=True, default='', help_text='Optional CDN address of the photo, used when no file is uploaded above. Lets existing photos stay on the university CDN instead of being re-uploaded.', max_length=500),
        ),
    ]
